#!/bin/python
import os
print "{0:4}| {1:20} | {2:15}".format("No","Interface","IP")
print "----+----------------------+----------------"
count = 1
for interface in os.listdir('/sys/class/net/'):
	if( len(os.popen("ip addr show " + interface).read().split("inet ")) > 1):
		print "{0:4}| {1:20} | {2:15}".format(count,interface,os.popen("ip addr show " + interface).read().split("inet ")[1].split("/")[0])
	else:
		print "{0:4}| {1:20} | {2:15}".format(count,interface,"-")
	count +=1
